services:
  - name: my-flask-app
    type: web
    envVars:
      - key: PORT
        value: "8080"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT wsgi:app
